#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WebService-Technorati
version:      0.02
version_from: lib/WebService/Technorati.pm
installdirs:  site
requires:
    Exception::Class:              1.19
    Test::Simple:                  0.44
    XML::XPath:                    1.13

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
